// <auto-generated />
namespace Gradebook.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fullnameChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fullnameChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202104142341510_fullnameChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
